### ISSUE TITLE
Supported ComputedPropertyName

### ISSUE THREAD

**Issue by CYBAI** [azu/ecmascript-version-detector#2]
As the example in [Ecmascript version detector](https://azu.github.io/ecmascript-version-detector/), there's a `computed property name` in line 9; however, it only shows object property in version 3. Will it be great to show `ComputedPropertyName` in version 2015? Thanks.

![image](https://cloud.githubusercontent.com/assets/6782666/16917311/b16c12b2-4d33-11e6-9650-6c5a593e4e53.png)

Reference:
- [MDN - Object Initializer#Computed Property Name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names)
- [ES6 Features - Computed Property Name](http://es6-features.org/#ComputedPropertyNames)

**Comment by azu** [comment]
https://github.com/babel/babylon/blob/master/ast/spec.md#objectproperty
ComputedPropertyName is `ObjectProperty` + `shorthand:true` on Babylon AST.
